root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ./cmd"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_file = ["air.toml"]
  delay = 500
